trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azureContainerRegistry'
    repository: 'dockeragent2'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build and Push docker image'
